### PR TITLE
Re vendor

### PR DESCRIPTION
**Pull request by bluecmd**
Now when there is a way to support vendoring with u-root, it's time!

Depending on https://github.com/u-root/u-bmc/pull/95

### CODE REVIEW

**Comment by hugelgupf** [comment]
Once you merge this, you actually can use the original u-root.go as well as u-bmc.go.

**Comment by bluecmd** [comment]
To mark this a bit more visibly: I would love to merge this, but the integration tests fails to compile with this change:

```
ckage)(0xc000b54aa0)}}: /go/src/github.com/u-root/u-bmc/integration/testdata/boot/uinit/test.go:14:2: could not import golang.org/x/sys/unix (cannot find package "golang.org/x/sys/unix" in any of:
        	/usr/local/go/src/golang.org/x/sys/unix (from $GOROOT)
        	/go/src/golang.org/x/sys/unix (from $GOPATH))
```

Note that there is no vendor root which usually would be there.

**Comment by hugelgupf** [comment]
I can't f***ing believe this, but... here's why it doesn't work:

Your uinit is in a src directory with the substring "testdata". When that's the case, vendoring is turned off. See https://github.com/golang/go/blob/c1a16b7dadfee27b03a2a70a20c3cf339a069a40/src/go/build/build.go#L562 for example.

If you rename your testdata directory to be something else (testcmd?), it should work fine.

**Comment by hugelgupf** [comment]
I can't believe it, but that fixed it.

**Comment by bluecmd** [comment]
Mind blown! Thanks folks, awesome :-)

**Pull request merged**
