### PR TITLE
gpio: Delay adding buttons to the Button map

### PR DESCRIPTION
**Pull request by Keno**
If a platform doesn't have all the buttons defined yet (e.g. because
it's in the process of being brought up), the PressButton rpc currently
hangs and never returns. I would have expected some sort of error message
and indeed the error handler for the button accessor:
```
	c, ok := g.Button[b]
	if !ok {
		return nil, fmt.Errorf("Unknown button %v", b)
	}
```
suggests that such an error message was indeed intended. However,
at the moment we're initializing the map for all buttons, so
`ok` is true, even if no button has ever been registered.
Switch that to not set up the map until the button was actually
registered, thus allowing above error case to fire.

### CODE REVIEW

**Comment by bluecmd** [comment]
@Keno Awesome stuff, thanks for fixing - definitely looks like the correct way. The tests fail with a concurrent write protection, which makes sense as all the buttons are run concurrently. What do you think about adding a lock to protect the initial section where the map is read/written?

**Comment by Keno** [comment]
That sounds good to me. Can I defer to you on the implementation thereof? I'm not familiar enough with go yet to get that right.

**Comment by bluecmd** [comment]
Sure, I can have a go (heh) at it.

**Comment by bluecmd** [comment]
Fixed in #183

**Pull request closed without merging**
